name: aya_abdelmoneim_portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  animate_do: ^4.2.0
  auto_size_text: ^3.0.0
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  flex_color_scheme: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  flutter_social_button: ^1.1.6+1
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  jwt_decoder: ^2.0.1
  path: ^1.9.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  text_gradiate: ^1.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/companies/
    - assets/images/projects/
    - assets/data/portfolio_data.json


  # TODO Fonts - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
